# Generated by Django 2.2.6 on 2019-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191011_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='products/'),
        ),
    ]
