# Generated by Django 2.2.6 on 2019-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_testproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproduct',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='myproducts/'),
        ),
    ]
