# Generated by Django 2.2.6 on 2019-10-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191012_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
    ]
