# Generated by Django 2.2.6 on 2019-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_testproduct_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='qtysizeL',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='testproduct',
            name='qtysizeM',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='testproduct',
            name='qtysizeS',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='testproduct',
            name='sizeXL',
            field=models.IntegerField(default=10),
        ),
    ]
