# Generated by Django 2.2.6 on 2019-11-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191116_1524'),
        ('billing', '0003_auto_20191116_1524'),
        ('products', '0012_auto_20191114_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
