# Generated by Django 2.2.6 on 2019-11-30 18:23

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=80, unique=True)),
                ('brandimage', models.ImageField(blank=True, null=True, upload_to=products.models.upload_brand_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='testproduct',
            name='brand',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
