# Generated by Django 2.2.6 on 2019-11-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191130_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='brand',
        ),
    ]
