# Generated by Django 2.2.6 on 2019-11-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_testproduct_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Brand'),
        ),
    ]
