# Generated by Django 2.2.6 on 2019-12-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191130_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproduct',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
