# Generated by Django 2.2.6 on 2019-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191203_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
